In [1]:
import numpy as np

In [9]:
x = np.array([[1,2,3],[4,5,6]])  # 两行三列的矩阵

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
x.dot(x.T)  # 矩阵相乘 2*3 dot 3*2 = 2*2

array([[14, 32],
       [32, 77]])

In [28]:
x.T.dot(x)  # 矩阵相乘 3*2 dot 2*3 = 3*3

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [13]:
x - 10  # 标量计算

array([[-9, -8, -7],
       [-6, -5, -4]])

In [14]:
x[:,1:3]  # 切片

array([[2, 3],
       [5, 6]])

In [19]:
np.mean(x),x.max(),x.min()  # 求均值，最大值，最小值

(3.5, 6, 1)

In [21]:
np.mean(x, axis=0)  # 求均值，按第一个轴，行相加

(array([2.5, 3.5, 4.5]), array([4, 5, 6]))

In [23]:
np.mean(x, axis=1)  # 求均值，按第二个轴，列相加

(array([2., 5.]), array([3, 6]))

In [30]:
x.max(),x.min()  # 求最大值，最小值

(6, 1)

In [31]:
x.max(axis=0), x.max(axis=1) # 按不同的轴取最值

(array([4, 5, 6]), array([3, 6]))